ler = input('Digite algo: ')
print('Seu tipo primitivo é', type(ler),'.')
print('É número?', ler.isnumeric())
print('É alphanumérico?', ler.isalnum())
print('É alpha?', ler.isalpha())
print('É ascii?', ler.isascii())
print('Todas letras são maiúsculas?', ler.isupper())
print('Todas letras são minúsculas?', ler.islower())
print('É somente espaços?', ler.isspace())
print('Está capitalizado?', ler.istitle())